version: 2

updates:
  - package-ecosystem: "uv"
    registries: "*"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    cooldown:
      include:
        - '*'
      default-days: 7
    groups:
      pytest-dependencies:
        patterns:
          - "pytest*"
      sphinx-dependencies:
        patterns:
          - "*sphinx*"

  - package-ecosystem: "github-actions"
    registries: "*"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      include:
        - '*'
      default-days: 7
    labels:
      - "maintenance"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      include:
        - '*'
      default-days: 7
    groups:
      pre-commit-deps:
        patterns:
          - "*"
