version: 2

registries:
  ansys-github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.PYANSYS_CI_BOT_TOKEN}}

updates:
  - package-ecosystem: "pip"
    insecure-external-code-execution: allow
    registries: "*"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"

    groups:
      pytest-dependencies:
        patterns:
          - "pytest*"

      sphinx-dependencies:
        patterns:
          - "*sphinx*"

  - package-ecosystem: "github-actions"
    registries: "*"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
    groups:
      actions-deps:
        patterns:
          - "*"
