repos:

- repo: https://github.com/astral-sh/ruff-pre-commit

  # Ruff version.
  rev: 0671d8ab202c4ac093b78433ae5baf74f3fc7246  # frozen: v0.15.15
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

# Add copyright statement to files
- repo: https://github.com/ansys/pre-commit-hooks
  rev: ad4e7598809ad98cde5aaf52d80040c7ac56e7cf  # frozen: v0.7.2
  hooks:
  - id: add-license-headers
    args:
    - --start_year=2026
    - --custom_license=Apache-2.0

- repo: https://github.com/codespell-project/codespell
  rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
  hooks:
  - id: codespell
    exclude: >
      (?x)^(
          .*\.csv|
          .*\.txt
      )$
    args: [-I, .codespellignore]

# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.3.0
#   hooks:
#   - id: pydocstyle
#     additional_dependencies: [toml]
#     exclude: "tests/"

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: f805888065fdb6162e1f800e50bb9460cbd223d6  # frozen: 0.37.2
  hooks:
    - id: check-github-workflows
