[build-system]
build-backend = "flit_core.buildapi"
requires = [ "flit-core>=4.0.2,<5" ]

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
name = "ansys-result-explorer-core"
version = "0.1.dev0"
description = "Python interface to Ansys Result Explorer"
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
maintainers = [ { name = "Synopsys, Inc. and ANSYS, Inc.", email = "pyansys-core@synopsys.com" } ]
authors = [ { name = "Synopsys, Inc. and ANSYS, Inc.", email = "pyansys-core@synopsys.com" } ]
requires-python = ">=3.12,<4.0"
classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "ansys-api-result-explorer==0.1.1",
  "grpcio>=1.63.0",
  "protobuf",
  "python-slugify>=8.0.4",
  "requests",
]
optional-dependencies.playwright = [ "playwright>=1.62.0" ]
urls.Homepage = "https://github.com/ansys/pyresultexplorer"
urls.Source = "https://github.com/ansys/pyresultexplorer"
urls.Tracker = "https://github.com/ansys/pyresultexplorer/issues"

[dependency-groups]
dev = [
  "pillow>=12.0.0",
  "pre-commit==4.6.2",
  "pytest==9.1.1",
  "pytest-cov==7.1.0",
  "pytest-playwright>=0.9.0",
  "pytest-rerunfailures==16.6",
  "syrupy>=5.3.4",
]
doc = [
  "ansys-sphinx-theme==1.10.0",
  "numpydoc==1.10.0",
  "pypandoc>=1.13",
  "sphinx==9.1.0",
  "sphinx-autobuild",
  "sphinx-copybutton==0.5.2",
  "sphinx-design>=0.6.1",
  "sphinx-gallery>=0.15.0",
]
examples = [
  "imageio",
  "ipython",
  "matplotlib",
]

[tool.flit]
module.name = "ansys.result_explorer.core"

[tool.uv]
default-groups = [ "dev" ]
cache-dir = "./.uv_cache"

[tool.ruff]
line-length = 100
extend-exclude = [ "src/ansys/result_explorer/core/protogen" ]
lint.select = [
  "B",       # flake8-bugbear
  "C4",      # flake8-comprehensions
  "D",       # pydocstyle
  "E",       # pycodestyle errors
  "F",       # pyflakes
  "I",       # isort
  "LOG",     # flake8-logging
  "N",       # pep8-naming
  "PLC",     # Pylint convention
  "PLE",     # Pylint errors
  "PLR1711", # useless-return
  "PLR5501", # collapsible-else-if
  "PLW",     # Pylint warnings
  "PT",      # flake8-pytest-style
  "Q",       # flake8-quotes
  "UP",      # pyupgrade
  "W",       # pycodestyle warnings
]
lint.ignore = []
lint.per-file-ignores.".github/scripts/*.py" = [ "E501" ]
lint.per-file-ignores."__init__.py" = [ "F401" ]
lint.per-file-ignores."examples/**/*.py" = [ "D", "PLC0415" ]
lint.per-file-ignores."src/**/models.py" = [ "F401" ]
# ignore docstring requirements for tests, examples
lint.per-file-ignores."tests/**/*.py" = [ "D", "PLC0415" ]

[tool.pytest]
ini_options.addopts = '-ra -vv -m "not images "'
ini_options.markers = [
  "images: marks tests that create or compare images (deselect with '-m \"not images\"')",
]
ini_options.filterwarnings = [
  "ignore::urllib3.exceptions.InsecureRequestWarning",
]
ini_options.log_cli = true
ini_options.log_cli_level = "DEBUG"
ini_options.log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
ini_options.log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.coverage]
run.source = [ "ansys.result_explorer" ]
run.omit = [ ".venv/*" ]
report.show_missing = true

[tool.towncrier]
package = "ansys.result_explorer.core"
directory = "doc/changelog.d"
filename = "doc/source/changelog.rst"
start_string = ".. towncrier release notes start\n"
template = "doc/changelog.d/changelog_template.jinja"
title_format = "`{version} <https://github.com/ansys/pyresultexplorer/releases/tag/v{version}>`_ - {project_date}"
issue_format = "`#{issue} <https://github.com/ansys/pyresultexplorer/pull/{issue}>`_"
type = [
  { directory = "breaking", name = "Breaking", showcontent = true },
  { directory = "added", name = "Added", showcontent = true },
  { directory = "fixed", name = "Fixed", showcontent = true },
  { directory = "documentation", name = "Documentation", showcontent = true },
  { directory = "dependencies", name = "Dependencies", showcontent = true },
  { directory = "maintenance", name = "Maintenance", showcontent = true },
  { directory = "miscellaneous", name = "Miscellaneous", showcontent = true },
  { directory = "test", name = "Test", showcontent = true },
  { directory = "changed", name = "Changed", showcontent = true },
]

[tool.pydocstyle]
convention = "numpy"
