"""Sphinx documentation configuration file."""

import glob
import os
import pathlib
import shutil
import sys
from datetime import datetime
from pathlib import Path

from ansys_sphinx_theme import ansys_favicon, get_version_match, pyansys_logo_black
from sphinx_gallery.scrapers import figure_rst

# Add src directory to path for autodoc to find modules
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))


from ansys.result_explorer.core import __version__

SKIP_GALLERY = os.environ.get("PYRX_DOC_SKIP_GALLERY", "1").lower() in ("1", "true")

# Suppress config cache warning for sphinx_gallery_conf (contains unpicklable function)
suppress_warnings = ["config.cache"]

# Project information
project = "ansys-result-explorer-core"
copyright = f"(c) {datetime.now().year} ANSYS, Inc. All rights reserved"
author = "ANSYS, Inc."
release = version = __version__
cname = os.getenv("DOCUMENTATION_CNAME", "https://pyresultexplorer.docs.pyansys.com")
switcher_version = get_version_match(__version__)

# Select desired logo, theme, and declare the html title
html_theme = "ansys_sphinx_theme"
html_short_title = html_title = "PyResultExplorer"
html_logo = pyansys_logo_black
html_favicon = ansys_favicon

# specify the location of your github repo
html_theme_options = {
    "github_url": "https://github.com/ansys-internal/pyresultexplorer",
    "show_prev_next": False,
    "show_breadcrumbs": True,
    "additional_breadcrumbs": [
        ("PyAnsys", "https://docs.pyansys.com/"),
    ],
    "switcher": {
        "json_url": f"https://{cname}/versions.json",
        "version_match": switcher_version,
    },
    "check_switcher": False,
    "logo": "pyansys",
    "collapse_navigation": False,
}

# Sphinx extensions
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "numpydoc",
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
    "sphinx_gallery.gen_gallery",
    "sphinx_design",
]

# autosummary configuration
autosummary_generate = True
autosummary_imported_members = True

# Intersphinx mapping
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    # kept here as an example
    # "scipy": ("https://docs.scipy.org/doc/scipy/reference", None),
    # "numpy": ("https://numpy.org/devdocs", None),
    # "matplotlib": ("https://matplotlib.org/stable", None),
    # "pandas": ("https://pandas.pydata.org/pandas-docs/stable", None),
    # "pyvista": ("https://docs.pyvista.org/", None),
    # "grpc": ("https://grpc.github.io/grpc/python/", None),
}

# sphinx-design configuration
sd_fontawesome_latex = True

# numpydoc configuration
numpydoc_show_class_members = False
numpydoc_xref_param_type = True

# Consider enabling numpydoc validation. See:
# https://numpydoc.readthedocs.io/en/latest/validation.html#
numpydoc_validate = True
numpydoc_validation_checks = {
    "GL06",  # Found unknown section
    "GL07",  # Sections are in the wrong order.
    "GL08",  # The object does not have a docstring
    "GL09",  # Deprecation warning should precede extended summary
    "GL10",  # reST directives {directives} must be followed by two colons
    "SS01",  # No summary found
    "SS02",  # Summary does not start with a capital letter
    # "SS03", # Summary does not end with a period
    "SS04",  # Summary contains heading whitespaces
    # "SS05", # Summary must start with infinitive verb, not third person
    "RT02",  # The first line of the Returns section should contain only the
    # type, unless multiple values are being returned"
}

if SKIP_GALLERY:
    # Generate the gallery without executing the code. The gallery will not
    # contain the output of the code cells.
    # This is useful for more quickly building the documentation.
    gallery_filename_pattern = "<MATCH NOTHING>"
else:
    gallery_filename_pattern = r".*\.py"

examples_dirs_base = pathlib.Path(__file__).parent.parent.parent / "examples"
gallery_dirs_base = pathlib.Path(__file__).parent / "examples"


def image_scraper(block, block_vars, gallery_conf, **kwargs):
    """Scrape PNG/GIF images generated by viewport snapshots.

    Captures all PNG and GIF files created during block execution and moves them
    to the gallery output directory using sphinx-gallery naming conventions.
    Automatically handles thumbnail selection and RST embedding.
    """
    # Get current working directory where examples execute
    cwd = os.getcwd()

    # Find all PNG and GIF files in the current directory
    png_files = sorted(glob.glob(os.path.join(cwd, "*.png")))
    gif_files = sorted(glob.glob(os.path.join(cwd, "*.gif")))
    image_files = png_files + gif_files

    if not image_files:
        return ""

    # Use sphinx-gallery's image_path_iterator to get properly-named output paths
    image_path_iterator = block_vars["image_path_iterator"]

    print(f"[image_scraper] Found {len(image_files)} image files")
    print(f"[image_scraper] Files: {[os.path.basename(f) for f in image_files]}")

    # Move image files to gallery output directory with sphinx-gallery naming
    output_paths = []
    for image_file in image_files:
        try:
            # Get the next output path from sphinx-gallery's iterator
            output_path = next(image_path_iterator)

            # If source is GIF, change the output extension to .gif
            if image_file.lower().endswith(".gif"):
                output_path = os.path.splitext(output_path)[0] + ".gif"

            if os.path.exists(image_file):
                basename = os.path.basename(image_file)
                print(f"  Moving: {basename} -> {os.path.basename(output_path)}")
                shutil.move(image_file, output_path)
                output_paths.append(output_path)
        except Exception as e:
            print(f"  Warning: Could not move {image_file}: {e}")

    if not output_paths:
        print("[image_scraper] No images were moved")
        return ""

    print(f"[image_scraper] Successfully moved {len(output_paths)} images")
    # Generate RST code for the images using figure_rst
    return figure_rst(output_paths, gallery_conf.get("src_dir", ""))


# sphinx gallery options
sphinx_gallery_conf = {
    # convert rst to md for ipynb (use sphinx-gallery's built-in converter)
    "pypandoc": False,
    # path to your examples scripts
    "examples_dirs": [str(examples_dirs_base)],
    # path where to save gallery generated examples
    "gallery_dirs": [str(gallery_dirs_base)],
    # Pattern to search for example files
    "filename_pattern": gallery_filename_pattern,
    # Remove the "Download all examples" button from the top level gallery
    "download_all_examples": False,
    # Sort gallery example by filename instead of number of lines (default)
    "within_subsection_order": "FileNameSortKey",
    # directory where function granular galleries are stored
    "backreferences_dir": "api/_gallery_backreferences",
    # Modules for which function level galleries are created.
    "doc_module": ("ansys.result_explorer.core"),
    "exclude_implicit_doc": {"ansys\\.result_explorer\\.core\\._.*"},  # ignore private submodules
    "image_scrapers": ("matplotlib", image_scraper),
    "ignore_pattern": r"(__init__\.py|060-create-hps-solution\.py)",
    "thumbnail_size": (320, 240),
    "remove_config_comments": True,
}

# static path
html_static_path = ["_static"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# Keep these while the repository is private
linkcheck_ignore = [
    "https://github.com/ansys-internal/pyresultexplorer/*",
    "https://pyresultexplorer.docs.pyansys.com/version/stable/*",
    "https://pypi.org/project/ansys-result-explorer-core",
]

# If we are on a release, we have to ignore the "release" URLs, since it is not
# available until the release is published.
if switcher_version != "dev":
    linkcheck_ignore.append(
        f"https://github.com/ansys-internal/pyresultexplorer/releases/tag/v{__version__}"
    )
