name: CI
on:
  workflow_dispatch:
    inputs:
      update-snapshots:
        description: 'Update snapshots'
        required: false
        default: false
        type: boolean
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"

env:
  MAIN_PYTHON_VERSION: '3.12'
  DOCUMENTATION_CNAME: 'fuzzy-adventure-gzkzk5l.pages.github.io'
  LIBRARY_NAME: 'ansys-result-explorer-core'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:

  update-changelog:
    name: "Update CHANGELOG (on release)"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push the CHANGELOG update commit, can be "read" once project is public
      pull-requests: write # Required to open the CHANGELOG update PR
    steps:
      - uses: ansys/actions/doc-deploy-changelog@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}


  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/code-style@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  doc-style:
    name: "Documentation Style Check"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: PyAnsys documentation style checks
        uses: ansys/actions/doc-style@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  actions-security:
    name: "Check Actions security"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/check-actions-security@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          generate-summary: true
          token: ${{ secrets.GITHUB_TOKEN }}
          auditing-level: 'high'

  # Job should be activated once the repo becomes public.
  # vulnerabilities:
  #   name: "Vulnerabilities"
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:

  #     - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3.0.0
  #       with:
  #         machine: github.com
  #         username: pyansys-ci-bot
  #         password: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

  #     - uses: ansys/actions/check-vulnerabilities@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
  #       with:
  #         python-version: ${{ env.MAIN_PYTHON_VERSION }}
  #         python-package-name: ${{ env.LIBRARY_NAME }}
  #         token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
  #         dev-mode: ${{ github.ref != 'refs/heads/main' }}

  tests-docker:
    name: "Tests Docker"
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
    with:
      deployment: docker
      update-snapshots: false
      python-versions: ${{ github.event_name == 'pull_request' && '["3.12"]' || '["3.11", "3.12", "3.13", "3.14"]' }}
      rx-version: 'v2026.7.0' # revert to dev after first release of PyRX
    secrets:
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
      PYANSYS_CI_BOT_USERNAME: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
      PYANSYS_CI_BOT_PACKAGE_TOKEN: ${{ secrets.PYANSYS_CI_BOT_PACKAGE_TOKEN }}
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}

  tests-native:
    name: "Tests Native"
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
    with:
      deployment: native
      update-snapshots: ${{ github.event_name == 'workflow_dispatch' && inputs.update-snapshots || false }}
      python-versions: ${{ github.event_name == 'pull_request' && '["3.12"]' || '["3.11", "3.12", "3.13", "3.14"]' }}
      upload-coverage: true
      rx-version: 'v2026.7.0' # revert to dev after first release of PyRX
    secrets:
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
  
  # enable after first release of PyRX
  # backward-compatibility-tests:
  #   strategy:
  #     matrix:
  #       rx-version: ['v2026.7.0']
  #     fail-fast: false
  #   uses: ./.github/workflows/tests.yml
  #   permissions:
  #     contents: read
  #   with:
  #     deployment: native
  #     update-snapshots: false
  #     python-versions: '["3.12"]'
  #     rx-version: ${{ matrix.rx-version }}
  #   secrets:
  #     PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
  #     LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}

  doc-build:
    name: "Build documentation"
    runs-on: ubuntu-latest-4-cores
    permissions:
      contents: read
    env:
      RX_SERVER_INSTALLATION_PATH: '/tmp/result-explorer-server'
    # needs: [doc-style]
    steps:

      - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3.0.0
        with:
          machine: github.com
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: "Install Result Explorer (native)"
        id: install-rx
        uses: ansys/pyresultexplorer/.github/actions/result-explorer-server@main # zizmor: ignore[unpinned-uses]
        with:
          version: 'latest-dev'
          installation-path: ${{ env.RX_SERVER_INSTALLATION_PATH }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - uses: ansys/actions/doc-build@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          optional-dependencies-name: "playwright"
          group-dependencies-name: "doc,examples"
          check-links: false
        env:
          ANSYS_RESULT_EXPLORER_SERVER: ${{ env.RX_SERVER_INSTALLATION_PATH }}/viz-server
          ANSYSLMD_LICENSE_FILE: 1055@${{ secrets.LICENSE_SERVER }}

  build-library:
    name: "Build library"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3.0.0
        with:
          machine: github.com
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: "Build library source and wheel artifacts"
        uses: ansys/actions/build-library@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          library-name: ${{ env.LIBRARY_NAME }}

  doc-deploy-dev:
    name: "Deploy development documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to deploy documentation to gh-pages
    needs: [doc-build, build-library, tests-docker, tests-native]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: ansys/actions/doc-deploy-dev@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  doc-deploy-stable:
    name: "Deploy stable documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to deploy documentation to gh-pages
    needs: [doc-build, build-library, tests-docker, tests-native]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    steps:
      - uses: ansys/actions/doc-deploy-stable@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  release:
    name: Release project
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [build-library]
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for PyPI trusted publishing (OIDC)
      contents: write  # Required to publish the GitHub release for the tagged version
    steps:
      - name: "Download the library artifacts from package step"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ env.LIBRARY_NAME }}-artifacts
          path: ${{ env.LIBRARY_NAME }}-artifacts

      - name: "Upload artifacts to PyPI using trusted publisher"
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          repository-url: "https://upload.pypi.org/legacy/"
          print-hash: true
          packages-dir: ${{ env.LIBRARY_NAME }}-artifacts
          skip-existing: false

      - name: Release to GitHub
        uses: ansys/actions/release-github@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}