name: CI
on:
  workflow_dispatch:
    inputs:
      update-snapshots:
        description: 'Update snapshots'
        required: false
        default: false
        type: boolean
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"

env:
  MAIN_PYTHON_VERSION: '3.12'
  DOCUMENTATION_CNAME: 'fuzzy-adventure-gzkzk5l.pages.github.io'
  LIBRARY_NAME: 'ansys-result-explorer-core'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:

  update-changelog:
    name: "Update CHANGELOG (on release)"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push the CHANGELOG update commit, can be "read" once project is public
      pull-requests: write # Required to open the CHANGELOG update PR
    steps:
      - uses: ansys/actions/doc-deploy-changelog@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}


  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/code-style@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  # doc-style:
  #   name: "Documentation Style Check"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: PyAnsys documentation style checks
  #       uses: ansys/actions/doc-style@v10.3.1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  actions-security:
    name: "Check Actions security"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/check-actions-security@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          generate-summary: true
          token: ${{ secrets.GITHUB_TOKEN }}
          auditing-level: 'high'

  vulnerabilities:
    name: Vulnerabilities
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UV_GITHUB_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
    steps:
      - uses: ansys/actions/check-vulnerabilities@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          python-package-name: ${{ env.LIBRARY_NAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          dev-mode: ${{ github.ref != 'refs/heads/main' }}

  tests-docker:
    name: "Tests Docker"
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
    with:
      deployment: docker
      update-snapshots: false
      python-versions: ${{ github.event_name == 'pull_request' && '["3.12"]' || '["3.11", "3.12", "3.13", "3.14"]' }}
    secrets:
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
      PYANSYS_CI_BOT_USERNAME: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
      PYANSYS_CI_BOT_PACKAGE_TOKEN: ${{ secrets.PYANSYS_CI_BOT_PACKAGE_TOKEN }}
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}

  tests-native:
    name: "Tests Native"
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
    with:
      deployment: native
      update-snapshots: ${{ github.event_name == 'workflow_dispatch' && inputs.update-snapshots || false }}
      python-versions: ${{ github.event_name == 'pull_request' && '["3.12"]' || '["3.11", "3.12", "3.13", "3.14"]' }}
    secrets:
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}

  doc-build:
    name: "Build documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # needs: [doc-style]
    steps:

      - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3.0.0
        with:
          machine: github.com
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - uses: ansys/actions/doc-build@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          optional-dependencies-name: ""
          group-dependencies-name: "doc"
          check-links: false

  build-library:
    name: "Build library"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3.0.0
        with:
          machine: github.com
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: "Build library source and wheel artifacts"
        uses: ansys/actions/build-library@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          library-name: ${{ env.LIBRARY_NAME }}

  doc-deploy-dev:
    name: "Deploy development documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to deploy documentation to gh-pages
    needs: [doc-build, build-library, tests-docker, tests-native]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: ansys/actions/doc-deploy-dev@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  doc-deploy-stable:
    name: "Deploy stable documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to deploy documentation to gh-pages
    needs: [doc-build, build-library, tests-docker, tests-native]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    steps:
      - uses: ansys/actions/doc-deploy-stable@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
