name: Tests (native)

on:
  workflow_call:
    inputs:
      update-snapshots:
        description: 'Update snapshots'
        required: false
        default: false
        type: boolean

env:
  MAIN_PYTHON_VERSION: '3.12'

jobs:
  tests:
    name: "Tests (native)"
    runs-on: ${{ matrix.os }}
    env:
      UPDATE_SNAPSHOTS: ${{ inputs.update-snapshots }}
    strategy:
      matrix:
       os: [ubuntu-latest] # can't run docker-compose on windows
       python-version: ['3.12'] # closer to release we can add other python versions
      fail-fast: false

    steps:

      - uses: actions/checkout@v6
        if: ${{ env.UPDATE_SNAPSHOTS != 'true' }}

      - uses: actions/checkout@v6
        if: ${{ env.UPDATE_SNAPSHOTS == 'true' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: Install Result Explorer
        id: install-rx
        uses: ./.github/actions/result-explorer-server
        with:
          version: 'latest-dev'
          installation-path: '/tmp/result-explorer-server'
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - uses: extractions/netrc@v3
        with:
          machine: github.com
          username: pyansys-ci-bot
          password: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          enable-cache: "false"

      - name: Install dependencies
        run: |
            uv sync --group dev --extra playwright

      - name: Run tests
        run: |
            ANSYS_RESULT_EXPLORER_SERVER=${{ steps.install-rx.outputs.exe-path }} pytest tests -m "" \
              --junitxml test_results_native.xml \
              --cov=ansys --cov-report=term --cov-report=html:.cov/html --cov-report=markdown:cov.md \
              ${{ env.UPDATE_SNAPSHOTS == 'true' && '--snapshot-update' || '' }} \
              --launch-native
        env:
          ANSYSLMD_LICENSE_FILE: 1055@${{ secrets.LICENSE_SERVER }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: '**/test*.xml'
          check_name: Test Report ${{ matrix.os }}:${{ matrix.python-version }} (native)
          detailed_summary: true
          include_passed: true

      - name: Show coverage report
        if: always()
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          cat cov.md >> $GITHUB_STEP_SUMMARY

      - name: Commit base images
        if: ${{ (success() || failure()) && env.UPDATE_SNAPSHOTS == 'true' }}
        uses: EndBug/add-and-commit@v10
        with:
          add: |
            tests/__snapshots__
          default_author: github_actions
          message: 'update snapshots'
          pull: '--ff-only'
          github_token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
